version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_arqsoft
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: basededatos_nicolas123
      MYSQL_DATABASE: arquisoftware
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: go_backend_arqsoft
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: basededatos_nicolas123
      DB_NAME: arquisoftware
    restart: on-failure

volumes:
  mysql_data:

